/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Accounts {
  cash_basis_role: "accrual" | "cash" | null;
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  normal_balance: "credit" | "debit";
  org_id: Buffer;
  parent_account_id: Buffer | null;
  type: "asset" | "equity" | "expense" | "liability" | "revenue";
  updated_at: Generated<Date>;
}

export interface ApAllocations {
  allocated_on: string;
  amount_minor: bigint;
  bill_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  id: Buffer;
  org_id: Buffer;
  payment_id: Buffer | null;
  updated_at: Generated<Date>;
  vendor_credit_id: Buffer | null;
}

export interface ApDocumentLineDimensions {
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  document_line_id: bigint;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface ApDocumentLines {
  account_id: Buffer;
  created_at: Generated<Date>;
  description: string | null;
  document_id: Buffer;
  id: Generated<bigint>;
  line_amount_minor: bigint;
  line_number: number;
  org_id: Buffer;
  quantity_micros: bigint;
  tax_amount_minor: bigint;
  tax_rate_id: Buffer | null;
  unit_amount_minor: bigint;
  updated_at: Generated<Date>;
}

export interface ApDocuments {
  contact_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  document_type: "bill" | "vendor_credit";
  due_date: string | null;
  id: Buffer;
  issue_date: string;
  journal_id: Buffer | null;
  memo: string | null;
  org_id: Buffer;
  reference: string | null;
  sequence_number: bigint | null;
  tax_mode: "exclusive" | "inclusive";
  updated_at: Generated<Date>;
  void_journal_id: Buffer | null;
}

export interface ApiKeys {
  created_at: Generated<Date>;
  created_by_user_id: Buffer | null;
  id: Buffer;
  key_hash: string;
  key_prefix: string;
  last_used_at: Date | null;
  name: string;
  org_id: Buffer;
  revoked_at: Date | null;
  role_id: Buffer;
}

export interface ArAllocations {
  allocated_on: string;
  amount_minor: bigint;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  credit_note_id: Buffer | null;
  id: Buffer;
  invoice_id: Buffer;
  org_id: Buffer;
  payment_id: Buffer | null;
  updated_at: Generated<Date>;
}

export interface ArDocumentLineDimensions {
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  document_line_id: bigint;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface ArDocumentLines {
  account_id: Buffer;
  created_at: Generated<Date>;
  description: string | null;
  document_id: Buffer;
  id: Generated<bigint>;
  line_amount_minor: bigint;
  line_number: number;
  org_id: Buffer;
  quantity_micros: bigint;
  tax_amount_minor: bigint;
  tax_rate_id: Buffer | null;
  unit_amount_minor: bigint;
  updated_at: Generated<Date>;
}

export interface ArDocuments {
  contact_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  document_type: "credit_note" | "invoice";
  due_date: string | null;
  id: Buffer;
  issue_date: string;
  journal_id: Buffer | null;
  memo: string | null;
  org_id: Buffer;
  reference: string | null;
  sequence_number: bigint | null;
  tax_mode: "exclusive" | "inclusive";
  updated_at: Generated<Date>;
  void_journal_id: Buffer | null;
}

export interface BankAccounts {
  account_id: Buffer;
  created_at: Generated<Date>;
  external_account_id: string | null;
  feed_source: Generated<"file">;
  id: Buffer;
  institution_name: string | null;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface BankImportMappings {
  amount_column: number | null;
  amount_convention: "debit_credit_columns" | "signed" | "signed_reversed";
  bank_account_id: Buffer;
  bank_reference_column: number | null;
  counterparty_column: number | null;
  created_at: Generated<Date>;
  credit_column: number | null;
  date_order: "dmy" | "mdy" | "ymd";
  debit_column: number | null;
  delimiter: Generated<string>;
  description_column: number;
  has_header_row: Generated<number>;
  id: Buffer;
  name: string;
  org_id: Buffer;
  posted_date_column: number;
  updated_at: Generated<Date>;
  value_date_column: number | null;
}

export interface BankLineClearings {
  cleared_amount_minor: bigint;
  cleared_journal_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  difference_account_id: Buffer | null;
  difference_amount_minor: bigint;
  difference_journal_id: Buffer | null;
  id: Buffer;
  method: "allocate_document" | "link_entry" | "post_entry";
  org_id: Buffer;
  payment_id: Buffer | null;
  reconciliation_session_id: Buffer | null;
  statement_line_id: Buffer;
  updated_at: Generated<Date>;
}

export interface BankMatchProposals {
  account_id: Buffer | null;
  ap_document_id: Buffer | null;
  ar_document_id: Buffer | null;
  bank_rule_id: Buffer | null;
  contact_id: Buffer | null;
  created_at: Generated<Date>;
  id: Buffer;
  journal_id: Buffer | null;
  org_id: Buffer;
  proposal_type: "ap_document" | "ar_document" | "coding" | "journal";
  rank: number;
  reason_code: string;
  statement_line_id: Buffer;
  updated_at: Generated<Date>;
}

export interface BankRuleDimensions {
  bank_rule_id: Buffer;
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface BankRules {
  bank_account_id: Buffer | null;
  created_at: Generated<Date>;
  id: Buffer;
  is_active: Generated<number>;
  match_amount_max_minor: bigint | null;
  match_amount_min_minor: bigint | null;
  match_description: string | null;
  match_description_mode: "contains" | "equals" | "starts_with" | null;
  match_direction: "inbound" | "outbound" | null;
  name: string;
  org_id: Buffer;
  priority: Generated<number>;
  set_account_id: Buffer;
  set_contact_id: Buffer | null;
  updated_at: Generated<Date>;
}

export interface BankStatementImports {
  bank_account_id: Buffer;
  closing_balance_minor: bigint | null;
  created_at: Generated<Date>;
  external_account_id: string | null;
  failure_reason: string | null;
  file_hash: string;
  filename: string;
  format: "csv" | "ofx";
  id: Buffer;
  imported_by_user_id: Buffer;
  lines_duplicate: number | null;
  lines_read: number | null;
  mapping_id: Buffer | null;
  org_id: Buffer;
  status: Generated<"complete" | "failed" | "processing" | "queued">;
  updated_at: Generated<Date>;
}

export interface BankStatementLines {
  amount_minor: bigint;
  bank_account_id: Buffer;
  bank_reference: string | null;
  counterparty: string | null;
  created_at: Generated<Date>;
  description: string;
  fingerprint: string;
  id: Buffer;
  import_id: Buffer;
  occurrence_index: Generated<number>;
  org_id: Buffer;
  posted_date: string;
  value_date: string | null;
}

export interface BillAttachments {
  ap_document_id: Buffer;
  byte_size: bigint;
  content_type: string;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  filename: string;
  id: Buffer;
  org_id: Buffer;
  storage_key: string;
}

export interface ChangeFeedCursors {
  created_at: Generated<Date>;
  id: Buffer;
  org_id: Buffer;
  position: Generated<bigint>;
  subscriber: string;
  updated_at: Generated<Date>;
}

export interface Contacts {
  code: string | null;
  created_at: Generated<Date>;
  display_name: string;
  email: string | null;
  id: Buffer;
  is_active: Generated<number>;
  is_customer: Generated<number>;
  is_vendor: Generated<number>;
  legal_name: string | null;
  notes: string | null;
  org_id: Buffer;
  phone: string | null;
  updated_at: Generated<Date>;
}

export interface Dimensions {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface DimensionValues {
  code: string;
  created_at: Generated<Date>;
  dimension_id: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface DocumentCaptures {
  byte_size: bigint;
  content_type: string;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  drafted_bill_id: Buffer | null;
  extracted_issue_date: string | null;
  extracted_reference: string | null;
  extracted_total_minor: bigint | null;
  extracted_vendor_name: string | null;
  extraction_error: string | null;
  extraction_json: Json | null;
  filename: string;
  id: Buffer;
  matched_contact_id: Buffer | null;
  org_id: Buffer;
  source: "email" | "upload";
  status: "dismissed" | "drafted" | "extracted" | "extracting" | "failed";
  storage_key: string;
  updated_at: Generated<Date>;
}

export interface DocumentSequences {
  document_type: "bill" | "credit_note" | "invoice" | "payment_paid" | "payment_received" | "vendor_credit";
  next_value: Generated<bigint>;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface DunningPolicies {
  created_at: Generated<Date>;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface DunningSends {
  created_at: Generated<Date>;
  id: Buffer;
  invoice_id: Buffer;
  org_id: Buffer;
  provider_message_id: string | null;
  recipient_email: string;
  sent_at: Generated<Date>;
  stage_id: Buffer;
  status: string;
}

export interface DunningStages {
  body: string;
  created_at: Generated<Date>;
  id: Buffer;
  late_fee_minor: bigint | null;
  offset_days: number;
  org_id: Buffer;
  policy_id: Buffer;
  stage_number: number;
  subject: string;
  updated_at: Generated<Date>;
}

export interface EventLog {
  actor_id: string;
  actor_type: string;
  id: Buffer;
  invocation_mode: string | null;
  name: string;
  occurred_at: Generated<Date>;
  org_id: Buffer;
  payload: Json;
  position: bigint;
}

export interface EventPositions {
  next_value: Generated<bigint>;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface ExternalRefs {
  created_at: Generated<Date>;
  entity_id: Buffer;
  entity_type: string;
  external_id: string;
  external_system: string;
  id: Buffer;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface FiscalPeriods {
  closed_at: Date | null;
  closed_by_user_id: Buffer | null;
  created_at: Generated<Date>;
  end_date: string;
  id: Buffer;
  name: string;
  org_id: Buffer;
  start_date: string;
  status: Generated<"closed" | "open">;
  updated_at: Generated<Date>;
}

export interface IdempotencyKeys {
  claim_scope: Generated<Buffer>;
  completed_at: Date | null;
  created_at: Generated<Date>;
  endpoint: string;
  expires_at: Date;
  id: Buffer;
  idempotency_key: string;
  org_id: Buffer | null;
  request_fingerprint: string;
  response_body: Json | null;
  response_status: number | null;
}

export interface InvoiceDeliveries {
  artifact_storage_key: string;
  created_at: Generated<Date>;
  id: Buffer;
  invoice_id: Buffer;
  key_prefix: string;
  org_id: Buffer;
  provider_message_id: string | null;
  recipient_email: string;
  sent_at: Generated<Date>;
  status: string;
  token_hash: Buffer;
}

export interface JournalDraftLineDimensions {
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  draft_line_id: bigint;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface JournalDraftLines {
  account_id: Buffer | null;
  contact_id: Buffer | null;
  created_at: Generated<Date>;
  credit_minor: bigint;
  debit_minor: bigint;
  draft_id: Buffer;
  id: Generated<bigint>;
  line_number: number;
  memo: string | null;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface JournalDrafts {
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  entry_date: string | null;
  id: Buffer;
  memo: string | null;
  org_id: Buffer;
  reference: string | null;
  updated_at: Generated<Date>;
}

export interface JournalLineDimensions {
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  journal_line_id: bigint;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface JournalLines {
  account_id: Buffer;
  contact_id: Buffer | null;
  created_at: Generated<Date>;
  credit_minor: bigint;
  debit_minor: bigint;
  id: Generated<bigint>;
  journal_id: Buffer;
  line_number: number;
  memo: string | null;
  org_id: Buffer;
}

export interface Journals {
  actor_id: Buffer;
  actor_type: "agent" | "automation" | "user";
  created_at: Generated<Date>;
  entry_date: string;
  id: Buffer;
  invocation_mode: "interactive" | "scheduled" | null;
  memo: string | null;
  org_id: Buffer;
  period_id: Buffer;
  reference: string | null;
  reverses_journal_id: Buffer | null;
  sequence_number: bigint;
  source: Generated<string>;
}

export interface JournalSequences {
  next_value: Generated<bigint>;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface OauthClients {
  client_id: string;
  created_at: Generated<Date>;
  created_by_user_id: Buffer | null;
  deactivated_at: Date | null;
  id: Buffer;
  name: string;
  org_id: Buffer;
  redirect_uris: Json;
  secret_hash: string;
  secret_prefix: string;
  updated_at: Generated<Date>;
}

export interface OauthConsents {
  client_id: Buffer;
  created_at: Generated<Date>;
  id: Buffer;
  org_id: Buffer;
  revoked_at: Date | null;
  scope: string;
  updated_at: Generated<Date>;
  user_id: Buffer;
}

export interface OauthGrants {
  client_id: Buffer;
  code_challenge: string;
  code_challenge_method: string;
  code_hash: string;
  consumed_at: Date | null;
  created_at: Generated<Date>;
  expires_at: Date;
  id: Buffer;
  org_id: Buffer;
  redirect_uri: string;
  scope: string;
  user_id: Buffer;
}

export interface OauthTokens {
  client_id: Buffer;
  created_at: Generated<Date>;
  expires_at: Date;
  id: Buffer;
  key_prefix: string;
  last_used_at: Date | null;
  org_id: Buffer;
  refresh_token_id: Buffer | null;
  revoked_at: Date | null;
  scope: string;
  token_hash: string;
  token_type: "access" | "refresh";
  user_id: Buffer;
}

export interface OrgAccountingSettings {
  created_at: Generated<Date>;
  default_reporting_basis: Generated<"accrual" | "cash">;
  org_id: Buffer;
  payable_control_account_id: Buffer | null;
  receivable_control_account_id: Buffer | null;
  updated_at: Generated<Date>;
}

export interface OrgBranding {
  address_line1: string | null;
  address_line2: string | null;
  brand_color: string | null;
  city: string | null;
  country: string | null;
  created_at: Generated<Date>;
  display_name: string;
  email: string | null;
  invoice_footer: string | null;
  logo_storage_key: string | null;
  org_id: Buffer;
  phone: string | null;
  postal_code: string | null;
  region: string | null;
  tax_number: string | null;
  updated_at: Generated<Date>;
  website: string | null;
}

export interface OrgInvites {
  accepted_at: Date | null;
  accepted_by_user_id: Buffer | null;
  created_at: Generated<Date>;
  email: string;
  expires_at: Date;
  id: Buffer;
  invited_by_user_id: Buffer | null;
  org_id: Buffer;
  revoked_at: Date | null;
  role_id: Buffer;
  token_hash: string;
}

export interface OrgMembers {
  created_at: Generated<Date>;
  invited_by_user_id: Buffer | null;
  org_id: Buffer;
  role_id: Buffer;
  updated_at: Generated<Date>;
  user_id: Buffer;
}

export interface Orgs {
  created_at: Generated<Date>;
  fiscal_year_start_month: Generated<number>;
  id: Buffer;
  inbound_email_token: Buffer | null;
  name: string;
  slug: string;
  updated_at: Generated<Date>;
}

export interface Payments {
  amount_minor: bigint;
  bank_account_id: Buffer;
  contact_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  direction: "paid" | "received";
  id: Buffer;
  journal_id: Buffer;
  memo: string | null;
  org_id: Buffer;
  payment_date: string;
  reference: string | null;
  sequence_number: bigint;
  updated_at: Generated<Date>;
  void_journal_id: Buffer | null;
}

export interface Permissions {
  code: string;
  description: string;
}

export interface ProcessorConnections {
  clearing_account_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  external_account_id: string | null;
  fee_account_id: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  last_polled_at: Date | null;
  org_id: Buffer;
  processor: "fake" | "square" | "stripe";
  publishable_key: string | null;
  reconciled_through: Date | null;
  secret_ref: string;
  updated_at: Generated<Date>;
  webhook_secret_ref: string;
}

export interface ProcessorEvents {
  connection_id: Buffer;
  event_type: "charge" | "dispute" | "fee" | "payout" | "refund";
  external_event_id: string;
  external_object_id: string;
  id: Buffer;
  org_id: Buffer;
  payload: Json;
  processed_at: Date | null;
  processing_error: string | null;
  processor: "fake" | "square" | "stripe";
  received_at: Generated<Date>;
  status: "failed" | "ignored" | "processed" | "received";
}

export interface ReconciliationSessionEvents {
  asserted_balance_minor: bigint | null;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  event_type: "finalised" | "reopened";
  id: Buffer;
  org_id: Buffer;
  reason: string | null;
  session_id: Buffer;
}

export interface ReconciliationSessions {
  bank_account_id: Buffer;
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  end_date: string;
  finalised_at: Date | null;
  id: Buffer;
  open_marker: Generated<Buffer | null>;
  org_id: Buffer;
  state: Generated<"finalised" | "in_progress">;
  statement_closing_balance_minor: bigint;
  updated_at: Generated<Date>;
}

export interface RecurringInvoiceTemplateLines {
  account_id: Buffer;
  created_at: Generated<Date>;
  description: string | null;
  id: Generated<bigint>;
  line_number: number;
  org_id: Buffer;
  quantity_micros: bigint;
  tax_rate_id: Buffer | null;
  template_id: Buffer;
  unit_amount_minor: bigint;
  updated_at: Generated<Date>;
}

export interface RecurringInvoiceTemplates {
  contact_id: Buffer;
  created_at: Generated<Date>;
  due_days: Generated<number>;
  end_date: string | null;
  frequency: string;
  id: Buffer;
  interval_count: Generated<number>;
  is_active: Generated<number>;
  last_run_date: string | null;
  materialization_mode: string;
  memo: string | null;
  name: string;
  next_run_date: string;
  org_id: Buffer;
  tax_mode: string;
  updated_at: Generated<Date>;
}

export interface RolePermissions {
  permission_code: string;
  role_id: Buffer;
}

export interface Roles {
  code: string;
  created_at: Generated<Date>;
  description: string;
  id: Buffer;
  is_system: Generated<number>;
  name: string;
  org_id: Buffer | null;
}

export interface Secrets {
  ciphertext: Buffer;
  created_at: Generated<Date>;
  name: string;
  updated_at: Generated<Date>;
}

export interface SecurityEvents {
  actor_user_id: Buffer | null;
  created_at: Generated<Date>;
  credential_id: Buffer | null;
  credential_type: string | null;
  detail: Json | null;
  event_type: string;
  id: Buffer;
  org_id: Buffer;
}

export interface Sessions {
  active_org_id: Buffer | null;
  created_at: Generated<Date>;
  expires_at: Date;
  id: Buffer;
  ip_address: Buffer | null;
  last_seen_at: Generated<Date>;
  revoked_at: Date | null;
  token_hash: string;
  user_agent: string | null;
  user_id: Buffer;
}

export interface TaxRates {
  applies_to: Generated<"both" | "purchases" | "sales">;
  created_at: Generated<Date>;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  rate_ppm: number;
  tax_account_id: Buffer;
  updated_at: Generated<Date>;
}

export interface Users {
  created_at: Generated<Date>;
  display_name: string;
  email: string;
  id: Buffer;
  is_active: Generated<number>;
  last_login_at: Date | null;
  password_hash: string;
  updated_at: Generated<Date>;
}

export interface DB {
  accounts: Accounts;
  ap_allocations: ApAllocations;
  ap_document_line_dimensions: ApDocumentLineDimensions;
  ap_document_lines: ApDocumentLines;
  ap_documents: ApDocuments;
  api_keys: ApiKeys;
  ar_allocations: ArAllocations;
  ar_document_line_dimensions: ArDocumentLineDimensions;
  ar_document_lines: ArDocumentLines;
  ar_documents: ArDocuments;
  bank_accounts: BankAccounts;
  bank_import_mappings: BankImportMappings;
  bank_line_clearings: BankLineClearings;
  bank_match_proposals: BankMatchProposals;
  bank_rule_dimensions: BankRuleDimensions;
  bank_rules: BankRules;
  bank_statement_imports: BankStatementImports;
  bank_statement_lines: BankStatementLines;
  bill_attachments: BillAttachments;
  change_feed_cursors: ChangeFeedCursors;
  contacts: Contacts;
  dimension_values: DimensionValues;
  dimensions: Dimensions;
  document_captures: DocumentCaptures;
  document_sequences: DocumentSequences;
  dunning_policies: DunningPolicies;
  dunning_sends: DunningSends;
  dunning_stages: DunningStages;
  event_log: EventLog;
  event_positions: EventPositions;
  external_refs: ExternalRefs;
  fiscal_periods: FiscalPeriods;
  idempotency_keys: IdempotencyKeys;
  invoice_deliveries: InvoiceDeliveries;
  journal_draft_line_dimensions: JournalDraftLineDimensions;
  journal_draft_lines: JournalDraftLines;
  journal_drafts: JournalDrafts;
  journal_line_dimensions: JournalLineDimensions;
  journal_lines: JournalLines;
  journal_sequences: JournalSequences;
  journals: Journals;
  oauth_clients: OauthClients;
  oauth_consents: OauthConsents;
  oauth_grants: OauthGrants;
  oauth_tokens: OauthTokens;
  org_accounting_settings: OrgAccountingSettings;
  org_branding: OrgBranding;
  org_invites: OrgInvites;
  org_members: OrgMembers;
  orgs: Orgs;
  payments: Payments;
  permissions: Permissions;
  processor_connections: ProcessorConnections;
  processor_events: ProcessorEvents;
  reconciliation_session_events: ReconciliationSessionEvents;
  reconciliation_sessions: ReconciliationSessions;
  recurring_invoice_template_lines: RecurringInvoiceTemplateLines;
  recurring_invoice_templates: RecurringInvoiceTemplates;
  role_permissions: RolePermissions;
  roles: Roles;
  secrets: Secrets;
  security_events: SecurityEvents;
  sessions: Sessions;
  tax_rates: TaxRates;
  users: Users;
}
