/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Accounts {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  normal_balance: "credit" | "debit";
  org_id: Buffer;
  parent_account_id: Buffer | null;
  type: "asset" | "equity" | "expense" | "liability" | "revenue";
  updated_at: Generated<Date>;
}

export interface ApiKeys {
  created_at: Generated<Date>;
  created_by_user_id: Buffer | null;
  id: Buffer;
  key_hash: string;
  key_prefix: string;
  last_used_at: Date | null;
  name: string;
  org_id: Buffer;
  revoked_at: Date | null;
  role_id: Buffer;
}

export interface Contacts {
  code: string | null;
  created_at: Generated<Date>;
  display_name: string;
  email: string | null;
  id: Buffer;
  is_active: Generated<number>;
  is_customer: Generated<number>;
  is_vendor: Generated<number>;
  legal_name: string | null;
  notes: string | null;
  org_id: Buffer;
  phone: string | null;
  updated_at: Generated<Date>;
}

export interface Dimensions {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface DimensionValues {
  code: string;
  created_at: Generated<Date>;
  dimension_id: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface FiscalPeriods {
  closed_at: Date | null;
  closed_by_user_id: Buffer | null;
  created_at: Generated<Date>;
  end_date: string;
  id: Buffer;
  name: string;
  org_id: Buffer;
  start_date: string;
  status: Generated<"closed" | "open">;
  updated_at: Generated<Date>;
}

export interface IdempotencyKeys {
  claim_scope: Generated<Buffer>;
  completed_at: Date | null;
  created_at: Generated<Date>;
  endpoint: string;
  expires_at: Date;
  id: Buffer;
  idempotency_key: string;
  org_id: Buffer | null;
  request_fingerprint: string;
  response_body: Json | null;
  response_status: number | null;
}

export interface JournalDraftLineDimensions {
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  draft_line_id: bigint;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface JournalDraftLines {
  account_id: Buffer | null;
  contact_id: Buffer | null;
  created_at: Generated<Date>;
  credit_minor: bigint;
  debit_minor: bigint;
  draft_id: Buffer;
  id: Generated<bigint>;
  line_number: number;
  memo: string | null;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface JournalDrafts {
  created_at: Generated<Date>;
  created_by_user_id: Buffer;
  entry_date: string | null;
  id: Buffer;
  memo: string | null;
  org_id: Buffer;
  reference: string | null;
  updated_at: Generated<Date>;
}

export interface JournalLineDimensions {
  created_at: Generated<Date>;
  dimension_id: Buffer;
  dimension_value_id: Buffer;
  journal_line_id: bigint;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface JournalLines {
  account_id: Buffer;
  contact_id: Buffer | null;
  created_at: Generated<Date>;
  credit_minor: bigint;
  debit_minor: bigint;
  id: Generated<bigint>;
  journal_id: Buffer;
  line_number: number;
  memo: string | null;
  org_id: Buffer;
}

export interface Journals {
  actor_id: Buffer;
  actor_type: "agent" | "automation" | "user";
  created_at: Generated<Date>;
  entry_date: string;
  id: Buffer;
  invocation_mode: "interactive" | "scheduled" | null;
  memo: string | null;
  org_id: Buffer;
  period_id: Buffer;
  reference: string | null;
  reverses_journal_id: Buffer | null;
  sequence_number: bigint;
  source: Generated<string>;
}

export interface JournalSequences {
  next_value: Generated<bigint>;
  org_id: Buffer;
  updated_at: Generated<Date>;
}

export interface OrgInvites {
  accepted_at: Date | null;
  accepted_by_user_id: Buffer | null;
  created_at: Generated<Date>;
  email: string;
  expires_at: Date;
  id: Buffer;
  invited_by_user_id: Buffer | null;
  org_id: Buffer;
  revoked_at: Date | null;
  role_id: Buffer;
  token_hash: string;
}

export interface OrgMembers {
  created_at: Generated<Date>;
  invited_by_user_id: Buffer | null;
  org_id: Buffer;
  role_id: Buffer;
  updated_at: Generated<Date>;
  user_id: Buffer;
}

export interface Orgs {
  created_at: Generated<Date>;
  fiscal_year_start_month: Generated<number>;
  id: Buffer;
  name: string;
  slug: string;
  updated_at: Generated<Date>;
}

export interface Permissions {
  code: string;
  description: string;
}

export interface RolePermissions {
  permission_code: string;
  role_id: Buffer;
}

export interface Roles {
  code: string;
  created_at: Generated<Date>;
  description: string;
  id: Buffer;
  is_system: Generated<number>;
  name: string;
  org_id: Buffer | null;
}

export interface Sessions {
  active_org_id: Buffer | null;
  created_at: Generated<Date>;
  expires_at: Date;
  id: Buffer;
  ip_address: Buffer | null;
  last_seen_at: Generated<Date>;
  revoked_at: Date | null;
  token_hash: string;
  user_agent: string | null;
  user_id: Buffer;
}

export interface Users {
  created_at: Generated<Date>;
  display_name: string;
  email: string;
  id: Buffer;
  is_active: Generated<number>;
  last_login_at: Date | null;
  password_hash: string;
  updated_at: Generated<Date>;
}

export interface DB {
  accounts: Accounts;
  api_keys: ApiKeys;
  contacts: Contacts;
  dimension_values: DimensionValues;
  dimensions: Dimensions;
  fiscal_periods: FiscalPeriods;
  idempotency_keys: IdempotencyKeys;
  journal_draft_line_dimensions: JournalDraftLineDimensions;
  journal_draft_lines: JournalDraftLines;
  journal_drafts: JournalDrafts;
  journal_line_dimensions: JournalLineDimensions;
  journal_lines: JournalLines;
  journal_sequences: JournalSequences;
  journals: Journals;
  org_invites: OrgInvites;
  org_members: OrgMembers;
  orgs: Orgs;
  permissions: Permissions;
  role_permissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  users: Users;
}
