import { expect, test } from '@playwright/test';

import { newRegistration } from './support/books';

/**
 * The QuickBooks-import narrative (Phase 3 — the launch gate), the milestone's browser
 * proof as D-26 asks: one run of user intent rather than a suite.
 *
 * A business arriving from QuickBooks brings three CSV exports — its chart of accounts, its
 * customers, and an opening trial balance — and expects to be posting the same day without
 * re-keying any of it. This drives exactly that: register, open the importer, hand it the
 * three files, preview what it would do, commit, and then read the trial balance to see the
 * opening journal it posted. The fiscal year is never generated by hand — the import does it
 * when the opening balance needs a period, which is the whole point of a one-click cutover.
 */

// A five-account chart. The two control types (Accounts Receivable / Accounts Payable) are
// nominated as the org's control accounts by the importer itself; the rest are ordinary.
const ACCOUNTS_CSV = `Name,Type,Number
Business checking,Bank,1000
Accounts receivable,Accounts Receivable,1100
Accounts payable,Accounts Payable,2000
Opening balance equity,Equity,3000
Consulting income,Income,4000
`;

const CUSTOMERS_CSV = `Name,Email
Acme Corp,ap@acme.test
`;

// A balanced opening trial balance: 7,000.00 of assets against 7,000.00 of equity. Each row
// names an account by its Number, which the chart above carries.
const TRIAL_BALANCE_CSV = `Account,Debit,Credit
1000,5000.00,
1100,2000.00,
3000,,7000.00
`;

function csv(name: string, contents: string): { name: string; mimeType: string; buffer: Buffer } {
  return { name, mimeType: 'text/csv', buffer: Buffer.from(contents, 'utf-8') };
}

test('a business migrates its chart, contacts and opening balances from QuickBooks', async ({
  page,
}) => {
  const registration = newRegistration();

  await test.step('register, which creates the login and the first organization together', async () => {
    await page.goto('/');
    await page.getByRole('button', { name: 'Create an account instead' }).click();
    await page.getByLabel('Your name').fill(registration.displayName);
    await page.getByLabel('Email').fill(registration.email);
    await page.getByLabel('Password').fill(registration.password);
    await page.getByLabel('Organization name').fill(registration.orgName);
    await page.getByRole('button', { name: 'Create account' }).click();

    await expect(page.getByRole('navigation', { name: 'Primary' })).toBeVisible();
  });

  await test.step('open the importer and hand it the three exports', async () => {
    await page.getByRole('link', { name: 'Import from QuickBooks' }).click();
    await expect(page.getByRole('heading', { name: 'Import from QuickBooks' })).toBeVisible();

    await page.getByLabel('Chart of accounts').setInputFiles(csv('accounts.csv', ACCOUNTS_CSV));
    await page.getByLabel('Customers').setInputFiles(csv('customers.csv', CUSTOMERS_CSV));
    await page.getByLabel('Trial balance').setInputFiles(csv('trial-balance.csv', TRIAL_BALANCE_CSV));
  });

  await test.step('preview shows what would be created, and that the opening balance balances', async () => {
    await page.getByRole('button', { name: 'Preview' }).click();

    const preview = page.getByRole('region', { name: 'Import preview' });
    await expect(preview.getByText('5 accounts to create')).toBeVisible();
    await expect(preview.getByText('1 customer, 0 vendors')).toBeVisible();
    // The trial balance is self-balancing (7,000.00 each side), so the importer will post it.
    await expect(preview.getByText('Balanced — ready to post as the opening journal.')).toBeVisible();
  });

  await test.step('commit the cutover — accounts, the customer, and the opening journal at once', async () => {
    await page.getByRole('button', { name: 'Import' }).click();

    const done = page.getByRole('status').filter({ hasText: 'Import complete.' });
    await expect(done).toBeVisible();
    await expect(done.getByText('5 accounts created')).toBeVisible();
    await expect(done.getByText('1 customer created')).toBeVisible();
    await expect(done.getByText('Opening journal posted')).toBeVisible();
  });

  await test.step('the trial balance now shows the opening balances the journal posted', async () => {
    // Two links say "Reports" now — the primary nav and the summary's "View reports" — so
    // this names the nav one exactly.
    await page.getByRole('link', { name: 'Reports', exact: true }).click();

    // Reports opens on the trial balance, and the opening journal is dated today, so the
    // as-at-today statement carries it. Each account the trial balance named now holds exactly
    // the figure it named — asserted as whole rows, which pins the account, its side and its
    // amount together (a bare "5000.00" cell repeats across the debit and balance columns).
    await expect(
      page.getByRole('row', { name: '1000 Business checking 5000.00 0.00 5000.00' }),
    ).toBeVisible();
    await expect(
      page.getByRole('row', { name: '1100 Accounts receivable 2000.00 0.00 2000.00' }),
    ).toBeVisible();
    await expect(
      page.getByRole('row', { name: '3000 Opening balance equity 0.00 7000.00 -7000.00' }),
    ).toBeVisible();
  });
});
