INSERT INTO ADDRESS
  (ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIPCODE, COUNTRY)
VALUES
  ('123 Main St', '', 'Miles City', 'MT', '59301', 'US'),
  ('404 W Shangrila Rd', '', 'Billings', 'MT', '59102', 'US');

INSERT INTO CUSTOMER_TYPE
  (DESC)
VALUES
  ('CONSUMER'),
  ('BUSINESS');

INSERT INTO CUSTOMER
  (CUSTOMER_TYPE_ID, NAME, FIRST_NAME, LAST_NAME, ADDRESS_ID, WEBSITE, EMAIL, PHONE)
VALUES
  (1, NULL, 'BOBBY', 'JO', 2, NULL, NULL, '406555123');

INSERT INTO COMPANY
  (COMPANY_NAME, TAX_ID, TAX_ID_TYPE, ADDRESS_ID, WEBSITE)
VALUES
  ('SAMS BAKERY', '123456789', 'EIN', 1, ''),
  ('SAMS OTHER LLC', '987654321', 'SSN', 1, '');

INSERT INTO COMPANY_CUSTOMER
  (COMPANY_ID, CUSTOMER_ID)
VALUES
  (1, 1),
  (2, 1);

INSERT INTO ACCOUNT
	(ACCOUNT_NUMBER, COMPANY_ID, NICKNAME, ACCOUNT_TYPE)
VALUES 
	('0001', 1, 'INVENTORY', 'ASSET'),
	('0002', 1, 'CASH', 'ASSET'),
	('0003', 2, 'BUILDING LOAN', 'LIABILITY');

INSERT INTO ACCOUNTING_ENTRY
  (ID)
VALUES (1), (2), (3), (4);

INSERT INTO ADJUSTMENT
	(ACCOUNT_ID, ACCOUNTING_ENTRY_ID, AMOUNT, TRANSACTION_TYPE)
VALUES
	(1, 1, 20.52, 'CREDIT'),(2, 1, 20.52, 'DEBIT'),
	(3, 2, 1023.98, 'DEBIT'),(1, 2, 1023.98, 'CREDIT'),
	(2, 3, 56.50, 'DEBIT'),(3, 3, 56.50, 'CREDIT'),
	(1, 4, 9.99, 'CREDIT'),(2, 4, 9.99, 'DEBIT');