DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ACCOUNTING_ENTRY;
DROP TABLE IF EXISTS ADJUSTMENT;

CREATE TABLE ADDRESS (
  ID INT IDENTITY PRIMARY KEY,
  ADDRESS_LINE1 VARCHAR(60) NOT NULL,
  ADDRESS_LINE2 VARCHAR(60),
  CITY VARCHAR(60) NOT NULL,
  STATE VARCHAR(20) NOT NULL,
  ZIPCODE VARCHAR(10) NOT NULL,
  COUNTRY VARCHAR(3) NOT NULL DEFAULT 'US'
);

CREATE TABLE CONTACT_PERSON (
  ID INT IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(40) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  ADDRESS_ID INT,
  EMAIL VARCHAR(80),
  PHONE VARCHAR(11),
  IS_PRIMARY BOOLEAN DEFAULT FALSE
);

CREATE TABLE CUSTOMER_TYPE (
  ID INT IDENTITY PRIMARY KEY,
  DESC VARCHAR(10) NOT NULL
);

CREATE TABLE CUSTOMER (
  ID INT IDENTITY PRIMARY KEY,
  CUSTOMER_TYPE_ID INT NOT NULL,
  NAME VARCHAR(40),
  FIRST_NAME VARCHAR(40),
  LAST_NAME VARCHAR(40),
  ADDRESS_ID INT,
  WEBSITE VARCHAR(80),
  EMAIL VARCHAR(80),
  PHONE VARCHAR(11),
  CONSTRAINT FK_CUSTOMER_CUSTOMER_TYPE FOREIGN KEY (CUSTOMER_TYPE_ID)
    REFERENCES CUSTOMER_TYPE(ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE CUSTOMER_CONTACT_PERSON (
  ID INT IDENTITY PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  CONTACT_PERSON_ID INT NOT NULL,
  CONSTRAINT FK_CUSTOMER_CONTACT_PERSON_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_CUSTOMER_CONTACT_PERSON_CONTACT_PERSON FOREIGN KEY (CONTACT_PERSON_ID)
    REFERENCES CONTACT_PERSON(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE COMPANY (
  ID INT IDENTITY PRIMARY KEY,
  COMPANY_NAME VARCHAR(50) NOT NULL,
  TAX_ID VARCHAR(9),
  TAX_ID_TYPE VARCHAR(4),
  ADDRESS_ID INT,
  WEBSITE VARCHAR(80),
  CONSTRAINT FK_COMPANY_ADDRESS FOREIGN KEY (ADDRESS_ID)
    REFERENCES ADDRESS(ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE COMPANY_CUSTOMER (
  ID INT IDENTITY PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  COMPANY_ID INT NOT NULL,
  CONSTRAINT FK_COMPANY_CUSTOMER_COMPANY FOREIGN KEY (COMPANY_ID)
    REFERENCES COMPANY(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_COMPANY_CUSTOMER_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ACCOUNT (
	ID INT IDENTITY PRIMARY KEY,
	COMPANY_ID INT NOT NULL,
	BALANCE NUMERIC(12,2) DEFAULT 0 NOT NULL,
	ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(50) NOT NULL,
	ACCOUNT_TYPE VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ACCOUNT_COMPANY FOREIGN KEY (COMPANY_ID)
    REFERENCES COMPANY(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE ACCOUNTING_ENTRY (
  ID INT IDENTITY PRIMARY KEY,
  ENTRY_NAME VARCHAR(50),
  NOTES VARCHAR(255)
);

CREATE TABLE ADJUSTMENT (
	ID INT IDENTITY PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
	ACCOUNTING_ENTRY_ID INT NOT NULL,
	AMOUNT NUMERIC(12,2) DEFAULT 0 NOT NULL,
	TRANSACTION_TYPE VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ACCOUNT_TRANSACTION FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT(ID)
	  ON DELETE CASCADE
	  ON UPDATE CASCADE,
	CONSTRAINT FK_ACCOUNTING_ENTRY_TRANSACTION FOREIGN KEY (ACCOUNTING_ENTRY_ID)
	  REFERENCES ACCOUNTING_ENTRY(ID)
	  ON DELETE CASCADE
	  ON UPDATE CASCADE
);

