DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE ACCOUNT (
	ID INT IDENTITY PRIMARY KEY,
	BALANCE NUMERIC(19,2) DEFAULT 0 NOT NULL,
	ACCOUNT_NUMBER VARCHAR(20) NOT NULL
);

CREATE TABLE TRANSACTION (
	ID INT IDENTITY PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
	CONSTRAINT FK_ACCOUNT_TRANSACTION FOREIGN KEY (ACCOUNT_ID)
	REFERENCES ACCOUNT(ID)
);

