import fc from 'fast-check';

import type { TestDatabase } from '../db';
import type { AccountPlan, Axis, Scene, SceneAccount } from '../reports/support';
import { createAxis, createChart, createScene, post } from '../reports/support';

import { ledgerPlanArb } from './arbitraries';
import type { AccountSpec, JournalPlan } from './support';

/**
 * Generated ledgers for the OB-041 properties.
 *
 * Built on `ledgerPlanArb` rather than beside it. That generator already knows how
 * to produce a journal the posting service will accept — balanced by construction,
 * amounts spanning the band above 2^53, dates inside the open period — and
 * re-deriving those bounds here would mean a property failing because the
 * *generator* was wrong, which proves nothing and hides everything. What is added
 * is the two things reports need and postings do not: a chart with a shape, and
 * tags.
 *
 * ## Why the hierarchy is generated by overriding types rather than by filtering
 *
 * A parent's type must equal its children's (`accounts/hierarchy.ts`), so a
 * generator that picked parents freely and discarded the mismatches would produce
 * an almost-flat chart — five independently generated types agree by accident
 * about a fifth of the time — and B7 would then mostly be asserted over trees with
 * no branches. Choosing a parent and *adopting its type* keeps every generated
 * chart as deep as the generator asked for. `normalBalance` is left independent,
 * so contra accounts still appear under an ordinary parent, which is the pair a
 * rollup that keyed off the normal balance rather than the type would get wrong.
 *
 * ## Why two axes
 *
 * One axis proves nothing about the row multiplication D-18 warned of: a line
 * carrying one tag joins once whether the join is right or wrong. Two axes, tagged
 * independently per line, mean a naive join doubles exactly the lines that carry
 * both — so a report that grouped by one axis while filtering on the other would
 * overstate, and the B6 property is what notices.
 */

export const AXIS_A_VALUES = 3;
export const AXIS_B_VALUES = 2;

export interface PlannedAccount {
  readonly type: AccountSpec['type'];
  readonly normalBalance: AccountSpec['normalBalance'];
  /** An index earlier in the list, or `null` for a root. */
  readonly parentIndex: number | null;
}

export interface PlannedTags {
  /** An index into axis A's values, or `null` for untagged on that axis. */
  readonly a: number | null;
  readonly b: number | null;
}

export interface ReportPlan {
  readonly accounts: readonly PlannedAccount[];
  readonly journals: readonly JournalPlan[];
  /** One entry per journal, one entry per line within it. */
  readonly tags: readonly (readonly PlannedTags[])[];
}

const tagsArb: fc.Arbitrary<PlannedTags> = fc.record({
  a: fc.option(fc.nat({ max: AXIS_A_VALUES - 1 }), { nil: null }),
  b: fc.option(fc.nat({ max: AXIS_B_VALUES - 1 }), { nil: null }),
});

export const reportPlanArb: fc.Arbitrary<ReportPlan> = ledgerPlanArb.chain((plan) => {
  const lineCount = plan.journals.reduce((total, journal) => total + journal.lines.length, 0);

  return fc
    .record({
      parents: fc.array(fc.option(fc.nat({ max: plan.accounts.length - 1 }), { nil: null }), {
        minLength: plan.accounts.length,
        maxLength: plan.accounts.length,
      }),
      // One flat run of tags, cut up per journal below. A tuple of per-journal
      // arrays would shrink each journal's tags independently, which sounds
      // better and is not: the line counts come from `plan`, so a shrink that
      // changed them would produce a plan whose tags no longer line up.
      tags: fc.array(tagsArb, { minLength: lineCount, maxLength: lineCount }),
    })
    .map(({ parents, tags }) => ({
      accounts: withHierarchy(plan.accounts, parents),
      journals: plan.journals,
      tags: cutPerJournal(plan.journals, tags),
    }));
});

function cutPerJournal(
  journals: readonly JournalPlan[],
  tags: readonly PlannedTags[],
): readonly (readonly PlannedTags[])[] {
  let offset = 0;
  return journals.map((journal) => {
    const slice = tags.slice(offset, offset + journal.lines.length);
    offset += journal.lines.length;
    return slice;
  });
}

export interface ReportRange {
  readonly from: string;
  readonly to: string;
}

/**
 * A plan together with a range whose bounds land on its own journal dates.
 *
 * The bounds are drawn from the plan's dates three times out of four rather than
 * uniformly from the year, and that weighting is the whole value of this
 * generator. Both bounds are inclusive, so the interesting question is what
 * happens to a journal posted on exactly `from` — it belongs to movement, not to
 * opening — and a range picked uniformly from 365 days coincides with one of at
 * most four journal dates about one run in a hundred. Measured: with uniform
 * bounds, changing the opening window's `<` to `<=` left every property in this
 * directory passing; with the bounds drawn from the plan, the same mutation fails
 * the opening property on the first run. A generator that never produces the
 * boundary case tests everything except the boundary.
 */
export const planWithRangeArb: fc.Arbitrary<{
  readonly plan: ReportPlan;
  readonly range: ReportRange;
}> = reportPlanArb.chain((plan) => {
  const dates = [...new Set(plan.journals.map((journal) => journal.date))];
  const bound =
    dates.length === 0
      ? dayOfYearArb()
      : fc.oneof(
          { withCrossShrink: true },
          { arbitrary: fc.constantFrom(...dates), weight: 3 },
          { arbitrary: dayOfYearArb(), weight: 1 },
        );

  return fc.tuple(bound, bound).map(([left, right]) => ({
    plan,
    range: left <= right ? { from: left, to: right } : { from: right, to: left },
  }));
});

function dayOfYearArb(): fc.Arbitrary<string> {
  const DAYS_IN_MONTH_2026 = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] as const;

  return fc
    .record({ month: fc.integer({ min: 1, max: 12 }), day: fc.integer({ min: 1, max: 31 }) })
    .map(({ month, day }) => {
      const lastDay = DAYS_IN_MONTH_2026[month - 1] ?? 28;
      return `2026-${pad(month)}-${pad(Math.min(day, lastDay))}`;
    });
}

function withHierarchy(
  specs: readonly AccountSpec[],
  parents: readonly (number | null)[],
): readonly PlannedAccount[] {
  const accounts: PlannedAccount[] = [];

  for (const [index, spec] of specs.entries()) {
    const choice = parents[index] ?? null;
    // Only an earlier account, so the chart is acyclic by construction and its
    // depth is bounded by the account count — which is below ACCOUNT_MAX_DEPTH.
    const parentIndex = choice !== null && choice < index ? choice : null;
    const parent = parentIndex === null ? undefined : accounts[parentIndex];

    accounts.push({
      type: parent?.type ?? spec.type,
      normalBalance: spec.normalBalance,
      parentIndex,
    });
  }

  return accounts;
}

export interface MaterializedLedger {
  readonly scene: Scene;
  readonly accounts: readonly SceneAccount[];
  readonly axisA: Axis;
  readonly axisB: Axis;
}

/**
 * Builds one generated plan into its own org.
 *
 * A fresh org per run, as `properties/support.ts` argues: the harness resets once
 * per `it` rather than once per run, so runs of the same property share a
 * database, and a new org is what keeps them independent. It also means the later
 * runs assert their property while several other orgs' postings sit in the same
 * tables, which is the state production is always in.
 */
export async function materialize(db: TestDatabase, plan: ReportPlan): Promise<MaterializedLedger> {
  const scene = await createScene(db);
  const axisA = await createAxis(scene, 'AXIS_A', valueCodes('A', AXIS_A_VALUES));
  const axisB = await createAxis(scene, 'AXIS_B', valueCodes('B', AXIS_B_VALUES));

  const chart = await createChart(scene, plan.accounts.map(toAccountPlan));
  const accounts = plan.accounts.map((_, index) => {
    const account = chart.get(accountCode(index));
    if (account === undefined) throw new Error(`Chart is missing account ${accountCode(index)}.`);
    return account;
  });

  for (const [journalIndex, journal] of plan.journals.entries()) {
    const journalTags = plan.tags[journalIndex] ?? [];

    await post(
      scene,
      journal.date,
      journal.lines.map((line, lineIndex) => {
        const account = accounts[line.accountIndex];
        if (account === undefined) throw new Error('Plan referenced an account it did not create.');

        const tags = journalTags[lineIndex];
        return {
          accountId: account.id,
          side: line.side,
          amount: line.amount,
          valueIds: tagValueIds(axisA, axisB, tags),
        };
      }),
    );
  }

  return { scene, accounts, axisA, axisB };
}

function toAccountPlan(account: PlannedAccount, index: number): AccountPlan {
  return {
    code: accountCode(index),
    type: account.type,
    normalBalance: account.normalBalance,
    ...(account.parentIndex === null ? {} : { parentCode: accountCode(account.parentIndex) }),
  };
}

function tagValueIds(axisA: Axis, axisB: Axis, tags: PlannedTags | undefined): readonly string[] {
  if (tags === undefined) return [];

  const ids: string[] = [];
  if (tags.a !== null) ids.push(valueId(axisA, 'A', tags.a));
  if (tags.b !== null) ids.push(valueId(axisB, 'B', tags.b));
  return ids;
}

function valueId(axis: Axis, prefix: string, index: number): string {
  const id = axis.values.get(`${prefix}${String(index)}`);
  if (id === undefined) throw new Error(`Axis is missing value ${prefix}${String(index)}.`);
  return id;
}

function valueCodes(prefix: string, count: number): readonly string[] {
  return Array.from({ length: count }, (_, index) => `${prefix}${String(index)}`);
}

/** Derived from position, so `uq_accounts_org_code` cannot reject a generated chart. */
export function accountCode(index: number): string {
  return String(1000 + index);
}

function pad(value: number): string {
  return String(value).padStart(2, '0');
}

/** The calendar day before `date`, for comparing an opening balance against `asOf`. */
export function dayBefore(date: string): string {
  const value = new Date(`${date}T00:00:00Z`);
  value.setUTCDate(value.getUTCDate() - 1);
  return value.toISOString().slice(0, 10);
}
