/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 while the process is listening and its HTTP stack is working. Reports no dependency state; see the source commentary for why.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the chart of accounts
         * @description One page, in `code` order — case-insensitive, so `1100` precedes `900`. Send back `nextCursor` verbatim for the next page; `null` means this was the last. Paging is safe against a cursor because `code` is immutable once an account exists (ROADMAP D-27): a sort column that could change would silently drop the rows that moved behind the cursor.
         */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Create an account
         * @description Accounts are created active. `normalBalance` is required and independent of `type`, because contra accounts are real — accumulated depreciation is an `asset` whose normal balance is `credit`.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One account */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /**
         * Delete an account that has never been posted to
         * @description An account is configuration rather than a record of what happened, so deleting an unreferenced one restates nothing. An account with postings answers `precondition_failed` with `account_has_postings`; deactivate it instead.
         */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /**
         * Update an account
         * @description `type` and `normalBalance` are refused once the account carries postings: changing either would silently restate what past reports said about entries already made.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/v1/accounts/{accountId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate an account
         * @description Removes an account from circulation without removing it from the books, which is the only form of removal available to an account that has been posted to. Idempotent: an already-inactive account is returned unchanged rather than refused.
         */
        post: operations["deactivateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate an account
         * @description The counterpart to deactivation, so that deactivation is not a one-way door.
         */
        post: operations["reactivateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a password for a session
         * @description Sets an `HttpOnly` session cookie. Every failure answers `unauthenticated` with no detail and takes the same time, because a faster answer for an unknown address is a user-enumeration oracle regardless of what the body says. Reachable without credentials.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session
         * @description Revokes the session named by the cookie and clears it. Succeeds whether or not the cookie names a live session — a stale cookie is the ordinary case for this call.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller, their organizations, the active one, and what they may do in it
         * @description Answers for any live session, including one whose user is a member of no organization — `activeOrgId` is then null and `permissions` is empty. `permissions` is advisory: it is what a screen hides buttons with, never what authorizes an operation (ROADMAP D-25).
         */
        get: operations["getCurrentIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a user and their first organization
         * @description Creates a user, their first organization, an Owner membership, and a session, atomically. Sets an `HttpOnly` session cookie; the token is never in the body. Reachable without credentials.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List fiscal periods */
        get: operations["listFiscalPeriods"];
        put?: never;
        /**
         * Create one monthly period
         * @description For the partial first year a business that started in September actually has. Gaplessness is a property of year generation, not of the table, so a year built one month at a time can leave a hole — and a date in that hole is un-postable.
         */
        post: operations["createFiscalPeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-periods/{periodId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close a fiscal period
         * @description The routine monthly soft close. Records who closed it and when. A posting dated inside a closed period is refused (A4), and a posting racing this call either commits fully or not at all (A9).
         */
        post: operations["closeFiscalPeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-periods/{periodId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen a closed fiscal period
         * @description Withdraws a statement that may already have been relied on, so it needs the separate `periods.reopen` permission rather than the one that closes.
         */
        post: operations["reopenFiscalPeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate the twelve periods of a fiscal year
         * @description The month the year begins in comes from the org’s `fiscalYearStartMonth`, not from the request — a caller that could choose it per call could generate two overlapping years for one org.
         */
        post: operations["generateFiscalYear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List posted journals
         * @description One page, oldest first by entry date and then by the org’s own entry number — the ordering `sequence_number` exists to make total (ROADMAP D-14). Send back `nextCursor` verbatim for the next page. Because the cursor names the last row seen rather than a count of rows behind it, an entry posted — or back-dated — while you page cannot cause a journal to be skipped or returned twice.
         */
        get: operations["listJournals"];
        put?: never;
        /**
         * Post a manual journal
         * @description At least two lines, debits equal to credits exactly, every account active and in this org, and the entry date inside an open fiscal period. All of it in one transaction, so a rejected posting leaves nothing behind.
         */
        post: operations["postJournal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journals/{journalId}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse a posted journal
         * @description Posts a new journal with every line’s side inverted and `reversesJournalId` set. The original is untouched. A journal may be reversed once; reversing the reversal re-instates the original.
         */
        post: operations["reverseJournal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every organization the caller is a member of
         * @description The org switcher’s menu. Always the full list with the role held in each, because one login may be Owner of its own books and Read-only on a client’s.
         */
        get: operations["listOrgMemberships"];
        put?: never;
        /**
         * Create an organization
         * @description Creates an organization with the calling user as its Owner. The slug is derived from the name and collisions are disambiguated silently, so no collision is ever reported.
         */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch the session’s active organization
         * @description Re-resolves the caller’s membership and points the session at the new org. An org the caller is not a member of and an org that does not exist both answer `not_found`.
         */
        post: operations["switchActiveOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trial balance
         * @description Debit and credit totals per account plus the org-wide totals, which must be equal. A direct aggregation over journal lines — there is no balance cache in M1, because a stale one produces books that balance on screen and not in the data.
         */
        get: operations["getTrialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One account in the org’s chart of accounts. */
        Account: {
            /** @description Short reference unique within the org, e.g. `1000`. Compared under the column's `utf8mb4_0900_ai_ci` collation, so it is case- and accent-insensitive: `1000a` and `1000A` are the same code. Leading and trailing whitespace is trimmed. */
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            /** Format: uuid */
            id: string;
            /** @description Inactive accounts keep every posting they carry and cannot be selected for new ones. This is the only form of removal available to an account that has been posted to. */
            isActive: boolean;
            /** @description Display name, e.g. `Operating bank account`. */
            name: string;
            /**
             * @description The side that increases this account. Stored, never derived from `type`, because contra accounts are real: accumulated depreciation is an `asset` whose normal balance is `credit`, as is an allowance for doubtful accounts. No constraint ties the two fields together — see the `accounts` commentary in migration 0002_ledger.
             * @enum {string}
             */
            normalBalance: "debit" | "credit";
            parentAccountId: string | null;
            /**
             * @description Which of the five statement categories the account belongs to. Determines where it appears in reports; it does not determine `normalBalance`.
             * @enum {string}
             */
            type: "asset" | "liability" | "equity" | "revenue" | "expense";
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description One account in the org’s chart of accounts. */
        AccountInput: {
            /** @description Short reference unique within the org, e.g. `1000`. Compared under the column's `utf8mb4_0900_ai_ci` collation, so it is case- and accent-insensitive: `1000a` and `1000A` are the same code. Leading and trailing whitespace is trimmed. */
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            /** Format: uuid */
            id: string;
            /** @description Inactive accounts keep every posting they carry and cannot be selected for new ones. This is the only form of removal available to an account that has been posted to. */
            isActive: boolean;
            /** @description Display name, e.g. `Operating bank account`. */
            name: string;
            /**
             * @description The side that increases this account. Stored, never derived from `type`, because contra accounts are real: accumulated depreciation is an `asset` whose normal balance is `credit`, as is an allowance for doubtful accounts. No constraint ties the two fields together — see the `accounts` commentary in migration 0002_ledger.
             * @enum {string}
             */
            normalBalance: "debit" | "credit";
            parentAccountId: string | null;
            /**
             * @description Which of the five statement categories the account belongs to. Determines where it appears in reports; it does not determine `normalBalance`.
             * @enum {string}
             */
            type: "asset" | "liability" | "equity" | "revenue" | "expense";
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description One page of the org’s chart of accounts, ordered by `code`. Comparison follows the column’s `utf8mb4_0900_ai_ci` collation, so it is case-insensitive and textual — `1100` sorts before `900`. Codes are immutable, which is what makes a cursor into this list stable while accounts are being created and edited. */
        AccountPage: {
            items: components["schemas"]["Account"][];
            /** @description The cursor for the next page, or `null` when this is the last one. Presence is the only signal that more exists — a full page does not imply another, and a short page never means a truncated answer. */
            nextCursor: components["schemas"]["PageCursor"] | null;
        };
        /** @description One page of the org’s chart of accounts, ordered by `code`. Comparison follows the column’s `utf8mb4_0900_ai_ci` collation, so it is case-insensitive and textual — `1100` sorts before `900`. Codes are immutable, which is what makes a cursor into this list stable while accounts are being created and edited. */
        AccountPageInput: {
            items: components["schemas"]["AccountInput"][];
            /** @description The cursor for the next page, or `null` when this is the last one. Presence is the only signal that more exists — a full page does not imply another, and a short page never means a truncated answer. */
            nextCursor: components["schemas"]["PageCursorInput"] | null;
        };
        /** @description The signed-in user. */
        AuthenticatedUser: {
            displayName: string;
            email: string;
            /** Format: uuid */
            id: string;
        };
        /** @description The signed-in user. */
        AuthenticatedUserInput: {
            displayName: string;
            email: string;
            /** Format: uuid */
            id: string;
        };
        /**
         * Format: date
         * @description A calendar date, `YYYY-MM-DD`. Not an instant: an accounting date carries no time and no timezone, because which fiscal period an entry lands in must not depend on the reader’s.
         * @example 2026-03-31
         */
        CalendarDate: string;
        /**
         * Format: date
         * @description A calendar date, `YYYY-MM-DD`. Not an instant: an accounting date carries no time and no timezone, because which fiscal period an entry lands in must not depend on the reader’s.
         * @example 2026-03-31
         */
        CalendarDateInput: string;
        /** @description The caller, their organizations, the active one, and the permission codes their role carries there. `permissions` is advisory — it is what a screen hides affordances with, never what authorizes an operation, which every service checks for itself. */
        CallerIdentity: {
            activeOrgId: string | null;
            memberships: components["schemas"]["OrgMembership"][];
            permissions: string[];
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @description The caller, their organizations, the active one, and the permission codes their role carries there. `permissions` is advisory — it is what a screen hides affordances with, never what authorizes an operation, which every service checks for itself. */
        CallerIdentityInput: {
            activeOrgId: string | null;
            memberships: components["schemas"]["OrgMembershipInput"][];
            permissions: string[];
            user: components["schemas"]["AuthenticatedUserInput"];
        };
        /** @description Creates one account. Accounts are created active, and top-level unless a `parentAccountId` is given. */
        CreateAccountRequest: {
            /** @description Short reference unique within the org, e.g. `1000`. Compared under the column's `utf8mb4_0900_ai_ci` collation, so it is case- and accent-insensitive: `1000a` and `1000A` are the same code. Leading and trailing whitespace is trimmed. */
            code: string;
            description?: string | null;
            /** @description Display name, e.g. `Operating bank account`. */
            name: string;
            /**
             * @description The side that increases this account. Stored, never derived from `type`, because contra accounts are real: accumulated depreciation is an `asset` whose normal balance is `credit`, as is an allowance for doubtful accounts. No constraint ties the two fields together — see the `accounts` commentary in migration 0002_ledger.
             * @enum {string}
             */
            normalBalance: "debit" | "credit";
            parentAccountId?: string | null;
            /**
             * @description Which of the five statement categories the account belongs to. Determines where it appears in reports; it does not determine `normalBalance`.
             * @enum {string}
             */
            type: "asset" | "liability" | "equity" | "revenue" | "expense";
        };
        /** @description Creates one account. Accounts are created active, and top-level unless a `parentAccountId` is given. */
        CreateAccountRequestInput: {
            /** @description Short reference unique within the org, e.g. `1000`. Compared under the column's `utf8mb4_0900_ai_ci` collation, so it is case- and accent-insensitive: `1000a` and `1000A` are the same code. Leading and trailing whitespace is trimmed. */
            code: string;
            description?: string | null;
            /** @description Display name, e.g. `Operating bank account`. */
            name: string;
            /**
             * @description The side that increases this account. Stored, never derived from `type`, because contra accounts are real: accumulated depreciation is an `asset` whose normal balance is `credit`, as is an allowance for doubtful accounts. No constraint ties the two fields together — see the `accounts` commentary in migration 0002_ledger.
             * @enum {string}
             */
            normalBalance: "debit" | "credit";
            parentAccountId?: string | null;
            /**
             * @description Which of the five statement categories the account belongs to. Determines where it appears in reports; it does not determine `normalBalance`.
             * @enum {string}
             */
            type: "asset" | "liability" | "equity" | "revenue" | "expense";
        };
        /** @description Creates one monthly period. A period is a calendar month, so it is named by year and month rather than by a date range. */
        CreateFiscalPeriodRequest: {
            /** @description Calendar month, 1–12. */
            month: number;
            /** @description The calendar year the fiscal year *starts* in. A year beginning in April 2026 and ending in March 2027 is fiscal year 2026. */
            year: number;
        };
        /** @description Creates one monthly period. A period is a calendar month, so it is named by year and month rather than by a date range. */
        CreateFiscalPeriodRequestInput: {
            /** @description Calendar month, 1–12. */
            month: number;
            /** @description The calendar year the fiscal year *starts* in. A year beginning in April 2026 and ending in March 2027 is fiscal year 2026. */
            year: number;
        };
        /** @description Creates an organization with the calling user as its Owner. No slug — it is derived from the name. */
        CreateOrgRequest: {
            /** @description The calendar month the org’s fiscal year begins in, 1–12. April, July, and October are all common. Defaults to January where the field is optional. */
            fiscalYearStartMonth?: number;
            /** @description Length is bounded by the server (`orgs.name` is `VARCHAR(255)`) and reported as a `validation_failed` naming `name`. */
            name: string;
        };
        /** @description Creates an organization with the calling user as its Owner. No slug — it is derived from the name. */
        CreateOrgRequestInput: {
            /** @description The calendar month the org’s fiscal year begins in, 1–12. April, July, and October are all common. Defaults to January where the field is optional. */
            fiscalYearStartMonth?: number;
            /** @description Length is bounded by the server (`orgs.name` is `VARCHAR(255)`) and reported as a `validation_failed` naming `name`. */
            name: string;
        };
        /** @description The body of every non-2xx response. */
        ErrorResponse: {
            error: {
                /**
                 * @description Stable machine-readable failure code. Integrators branch on this, not on the HTTP status: `conflict` and `idempotency_key_conflict` are both 409 and have different recoveries. Codes are never renamed and never change status.
                 * @enum {string}
                 */
                code: "validation_failed" | "unauthenticated" | "permission_denied" | "not_found" | "conflict" | "idempotency_key_conflict" | "precondition_failed" | "internal_error";
                details?: {
                    [key: string]: unknown;
                };
                message: string;
            };
        };
        /** @description The body of every non-2xx response. */
        ErrorResponseInput: {
            error: {
                /**
                 * @description Stable machine-readable failure code. Integrators branch on this, not on the HTTP status: `conflict` and `idempotency_key_conflict` are both 409 and have different recoveries. Codes are never renamed and never change status.
                 * @enum {string}
                 */
                code: "validation_failed" | "unauthenticated" | "permission_denied" | "not_found" | "conflict" | "idempotency_key_conflict" | "precondition_failed" | "internal_error";
                details?: {
                    [key: string]: unknown;
                };
                message: string;
            };
        };
        /** @description One monthly fiscal period. */
        FiscalPeriod: {
            closedAt: string | null;
            closedByUserId: string | null;
            endDate: components["schemas"]["CalendarDate"];
            /** Format: uuid */
            id: string;
            /** @description Human label for the month, e.g. `2026-03`. */
            name: string;
            startDate: components["schemas"]["CalendarDate"];
            /**
             * @description A posting may only land in an `open` period (A4). Closing is the routine monthly soft close; reopening withdraws a statement that may already have been relied on, and needs a separate permission.
             * @enum {string}
             */
            status: "open" | "closed";
        };
        /** @description One monthly fiscal period. */
        FiscalPeriodInput: {
            closedAt: string | null;
            closedByUserId: string | null;
            endDate: components["schemas"]["CalendarDateInput"];
            /** Format: uuid */
            id: string;
            /** @description Human label for the month, e.g. `2026-03`. */
            name: string;
            startDate: components["schemas"]["CalendarDateInput"];
            /**
             * @description A posting may only land in an `open` period (A4). Closing is the routine monthly soft close; reopening withdraws a statement that may already have been relied on, and needs a separate permission.
             * @enum {string}
             */
            status: "open" | "closed";
        };
        /** @description The org’s fiscal periods in ascending date order. Unpaginated in M1. */
        FiscalPeriodList: {
            periods: components["schemas"]["FiscalPeriod"][];
        };
        /** @description The org’s fiscal periods in ascending date order. Unpaginated in M1. */
        FiscalPeriodListInput: {
            periods: components["schemas"]["FiscalPeriodInput"][];
        };
        /** @description Generates the twelve monthly periods of one fiscal year. Generation is always explicit — no posting ever creates the period it needs (ROADMAP D-17). */
        GenerateFiscalYearRequest: {
            /** @description The calendar year the fiscal year *starts* in. A year beginning in April 2026 and ending in March 2027 is fiscal year 2026. */
            fiscalYear: number;
        };
        /** @description Generates the twelve monthly periods of one fiscal year. Generation is always explicit — no posting ever creates the period it needs (ROADMAP D-17). */
        GenerateFiscalYearRequestInput: {
            /** @description The calendar year the fiscal year *starts* in. A year beginning in April 2026 and ending in March 2027 is fiscal year 2026. */
            fiscalYear: number;
        };
        /** @description The generated fiscal year, its span, and the twelve periods inside it. */
        GeneratedFiscalYear: {
            endDate: components["schemas"]["CalendarDate"];
            /** @description The calendar year the fiscal year *starts* in. A year beginning in April 2026 and ending in March 2027 is fiscal year 2026. */
            fiscalYear: number;
            /** @description Twelve periods, contiguous, in ascending date order. */
            periods: components["schemas"]["FiscalPeriod"][];
            startDate: components["schemas"]["CalendarDate"];
            startMonth: number;
        };
        /** @description The generated fiscal year, its span, and the twelve periods inside it. */
        GeneratedFiscalYearInput: {
            endDate: components["schemas"]["CalendarDateInput"];
            /** @description The calendar year the fiscal year *starts* in. A year beginning in April 2026 and ending in March 2027 is fiscal year 2026. */
            fiscalYear: number;
            /** @description Twelve periods, contiguous, in ascending date order. */
            periods: components["schemas"]["FiscalPeriodInput"][];
            startDate: components["schemas"]["CalendarDateInput"];
            startMonth: number;
        };
        /** @description The caller, every organization they are a member of, and which one this session is currently scoped to. `activeOrgId` is null for a user who is a member of nothing. */
        Identity: {
            activeOrgId: string | null;
            memberships: components["schemas"]["OrgMembership"][];
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @description The caller, every organization they are a member of, and which one this session is currently scoped to. `activeOrgId` is null for a user who is a member of nothing. */
        IdentityInput: {
            activeOrgId: string | null;
            memberships: components["schemas"]["OrgMembershipInput"][];
            user: components["schemas"]["AuthenticatedUserInput"];
        };
        /** @description One side of one account, for a positive amount in minor units. */
        JournalLineRequest: {
            /** Format: uuid */
            accountId: string;
            amount: components["schemas"]["MinorUnits"];
            memo?: string;
            /**
             * @description Which side of the ledger this line moves. The side carries the sign, so `amount` is always positive — a negative credit is not a debit, it is a caller that has confused the two models.
             * @enum {string}
             */
            side: "debit" | "credit";
        };
        /** @description One side of one account, for a positive amount in minor units. */
        JournalLineRequestInput: {
            /** Format: uuid */
            accountId: string;
            amount: components["schemas"]["MinorUnitsInput"];
            memo?: string;
            /**
             * @description Which side of the ledger this line moves. The side carries the sign, so `amount` is always positive — a negative credit is not a debit, it is a caller that has confused the two models.
             * @enum {string}
             */
            side: "debit" | "credit";
        };
        /** @description One page of posted journals, oldest first by entry date and then by the org’s entry number. Both ordering columns are immutable, so a cursor into this list stays exact while entries — including back-dated ones — are being posted. */
        JournalPage: {
            items: components["schemas"]["JournalSummary"][];
            /** @description The cursor for the next page, or `null` when this is the last one. Presence is the only signal that more exists — a full page does not imply another, and a short page never means a truncated answer. */
            nextCursor: components["schemas"]["PageCursor"] | null;
        };
        /** @description One page of posted journals, oldest first by entry date and then by the org’s entry number. Both ordering columns are immutable, so a cursor into this list stays exact while entries — including back-dated ones — are being posted. */
        JournalPageInput: {
            items: components["schemas"]["JournalSummaryInput"][];
            /** @description The cursor for the next page, or `null` when this is the last one. Presence is the only signal that more exists — a full page does not imply another, and a short page never means a truncated answer. */
            nextCursor: components["schemas"]["PageCursorInput"] | null;
        };
        /** @description One posted journal, without its lines. */
        JournalSummary: {
            /** Format: uuid */
            actorId: string;
            /** @enum {string} */
            actorType: "user" | "automation" | "agent";
            date: components["schemas"]["CalendarDate"];
            /** Format: uuid */
            journalId: string;
            memo: string | null;
            /**
             * Format: date-time
             * @description When the journal was written. An instant, not an accounting date.
             */
            postedAt: string;
            /** @description Set when this journal reverses another. The link lives on the reversing journal because the original cannot be updated (ROADMAP D-02). */
            reversesJournalId: string | null;
            /** @description The org’s own gapless entry number (ROADMAP D-14). Monotonic, unique within the org, and the second half of this list’s ordering — `entryDate` alone is not total. */
            sequenceNumber: string;
            /** @description `manual` for an entry a person posted, `reversal` for one posted by reversing. */
            source: string;
        };
        /** @description One posted journal, without its lines. */
        JournalSummaryInput: {
            /** Format: uuid */
            actorId: string;
            /** @enum {string} */
            actorType: "user" | "automation" | "agent";
            date: components["schemas"]["CalendarDateInput"];
            /** Format: uuid */
            journalId: string;
            memo: string | null;
            /**
             * Format: date-time
             * @description When the journal was written. An instant, not an accounting date.
             */
            postedAt: string;
            /** @description Set when this journal reverses another. The link lives on the reversing journal because the original cannot be updated (ROADMAP D-02). */
            reversesJournalId: string | null;
            /** @description The org’s own gapless entry number (ROADMAP D-14). Monotonic, unique within the org, and the second half of this list’s ordering — `entryDate` alone is not total. */
            sequenceNumber: string;
            /** @description `manual` for an entry a person posted, `reversal` for one posted by reversing. */
            source: string;
        };
        /** @description Exchanges a password for a session cookie. Reachable without credentials. Every failure answers `unauthenticated` with no detail — a wrong password and an unknown address are indistinguishable by design. */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description Exchanges a password for a session cookie. Reachable without credentials. Every failure answers `unauthenticated` with no detail — a wrong password and an unknown address are indistinguishable by design. */
        LoginRequestInput: {
            email: string;
            password: string;
        };
        /**
         * @description An exact monetary amount as a string of minor units — an integer count of cents with no decimal point, no separators, and no leading zeros. `"150000"` is 1,500.00 in a two-decimal currency. Never a JSON number, and never a decimal amount: `"1500.00"` is refused.
         * @example 150000
         * @example -150000
         * @example 0
         */
        MinorUnits: string;
        /**
         * @description An exact monetary amount as a string of minor units — an integer count of cents with no decimal point, no separators, and no leading zeros. `"150000"` is 1,500.00 in a two-decimal currency. Never a JSON number, and never a decimal amount: `"1500.00"` is refused.
         * @example 150000
         * @example -150000
         * @example 0
         */
        MinorUnitsInput: string;
        /** @description One organization together with the role the caller holds in it. */
        OrgMembership: {
            org: components["schemas"]["OrgSummary"];
            roleCode: string;
            /** Format: uuid */
            roleId: string;
        };
        /** @description One organization together with the role the caller holds in it. */
        OrgMembershipInput: {
            org: components["schemas"]["OrgSummaryInput"];
            roleCode: string;
            /** Format: uuid */
            roleId: string;
        };
        /** @description Every organization the caller is a member of, with the role held in each. */
        OrgMembershipList: {
            memberships: components["schemas"]["OrgMembership"][];
        };
        /** @description Every organization the caller is a member of, with the role held in each. */
        OrgMembershipListInput: {
            memberships: components["schemas"]["OrgMembershipInput"][];
        };
        /** @description One organization the caller can act in. */
        OrgSummary: {
            /** @description The calendar month the org’s fiscal year begins in, 1–12. April, July, and October are all common. Defaults to January where the field is optional. */
            fiscalYearStartMonth: number;
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        /** @description One organization the caller can act in. */
        OrgSummaryInput: {
            /** @description The calendar month the org’s fiscal year begins in, 1–12. April, July, and October are all common. Defaults to January where the field is optional. */
            fiscalYearStartMonth: number;
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        /** @description An opaque position in a list. Send back the `nextCursor` of the previous page verbatim to get the next one. Do not parse it, construct it, or store it: its contents are the server’s ordering columns and they are free to change. */
        PageCursor: string;
        /** @description An opaque position in a list. Send back the `nextCursor` of the previous page verbatim to get the next one. Do not parse it, construct it, or store it: its contents are the server’s ordering columns and they are free to change. */
        PageCursorInput: string;
        /** @description Posts one manual journal. At least two lines, and debits must equal credits exactly — there is no tolerance, because in minor units there is nothing for a tolerance to absorb. */
        PostJournalRequest: {
            /** @description The entry date. It must fall inside an open fiscal period — periods are never created as a side effect of posting (ROADMAP D-17), so the year has to be generated first. */
            date: components["schemas"]["CalendarDate"];
            lines: components["schemas"]["JournalLineRequest"][];
            memo?: string;
        };
        /** @description Posts one manual journal. At least two lines, and debits must equal credits exactly — there is no tolerance, because in minor units there is nothing for a tolerance to absorb. */
        PostJournalRequestInput: {
            /** @description The entry date. It must fall inside an open fiscal period — periods are never created as a side effect of posting (ROADMAP D-17), so the year has to be generated first. */
            date: components["schemas"]["CalendarDateInput"];
            lines: components["schemas"]["JournalLineRequestInput"][];
            memo?: string;
        };
        /** @description A journal as the ledger stored it, read back from the same transaction. */
        PostedJournal: {
            /** Format: uuid */
            actorId: string;
            /**
             * @description Who or what made the posting (spec §6). Taken from the session, never from the request.
             * @enum {string}
             */
            actorType: "user" | "automation" | "agent";
            date: components["schemas"]["CalendarDate"];
            /** @description Whether a human was present. Null means unrecorded, which is not the same as `interactive`. Set for agent callers only. */
            invocationMode: ("interactive" | "scheduled") | null;
            /** Format: uuid */
            journalId: string;
            lines: components["schemas"]["PostedJournalLine"][];
            memo: string | null;
            /** Format: uuid */
            orgId: string;
            /**
             * Format: date-time
             * @description When the journal was written. An instant, not an accounting date.
             */
            postedAt: string;
            /** @description Set when this journal reverses another. The link lives on the reversing journal because the original cannot be updated (ROADMAP D-02). */
            reversesJournalId: string | null;
        };
        /** @description A journal as the ledger stored it, read back from the same transaction. */
        PostedJournalInput: {
            /** Format: uuid */
            actorId: string;
            /**
             * @description Who or what made the posting (spec §6). Taken from the session, never from the request.
             * @enum {string}
             */
            actorType: "user" | "automation" | "agent";
            date: components["schemas"]["CalendarDateInput"];
            /** @description Whether a human was present. Null means unrecorded, which is not the same as `interactive`. Set for agent callers only. */
            invocationMode: ("interactive" | "scheduled") | null;
            /** Format: uuid */
            journalId: string;
            lines: components["schemas"]["PostedJournalLineInput"][];
            memo: string | null;
            /** Format: uuid */
            orgId: string;
            /**
             * Format: date-time
             * @description When the journal was written. An instant, not an accounting date.
             */
            postedAt: string;
            /** @description Set when this journal reverses another. The link lives on the reversing journal because the original cannot be updated (ROADMAP D-02). */
            reversesJournalId: string | null;
        };
        /** @description One stored line. `side` is read back from which amount column is non-zero rather than echoed from the request, so this reports what the ledger holds. */
        PostedJournalLine: {
            /** Format: uuid */
            accountId: string;
            amount: components["schemas"]["MinorUnits"];
            contactId: string | null;
            /** @description The dimension values this line carries, named by value — a value belongs to exactly one axis, so the pair is never sent. Written with the line and read back from the tag table; changing them afterwards is the dimensions surface (ROADMAP D-32). */
            dimensionValueIds: string[];
            lineId: string;
            memo: string | null;
            /**
             * @description Which side of the ledger this line moves. The side carries the sign, so `amount` is always positive — a negative credit is not a debit, it is a caller that has confused the two models.
             * @enum {string}
             */
            side: "debit" | "credit";
        };
        /** @description One stored line. `side` is read back from which amount column is non-zero rather than echoed from the request, so this reports what the ledger holds. */
        PostedJournalLineInput: {
            /** Format: uuid */
            accountId: string;
            amount: components["schemas"]["MinorUnitsInput"];
            contactId: string | null;
            /** @description The dimension values this line carries, named by value — a value belongs to exactly one axis, so the pair is never sent. Written with the line and read back from the tag table; changing them afterwards is the dimensions surface (ROADMAP D-32). */
            dimensionValueIds: string[];
            lineId: string;
            memo: string | null;
            /**
             * @description Which side of the ledger this line moves. The side carries the sign, so `amount` is always positive — a negative credit is not a debit, it is a caller that has confused the two models.
             * @enum {string}
             */
            side: "debit" | "credit";
        };
        /** @description Creates a user, their first organization, an Owner membership, and a session — atomically. Reachable without credentials. */
        RegisterRequest: {
            displayName: string;
            email: string;
            org: components["schemas"]["CreateOrgRequest"];
            password: string;
        };
        /** @description Creates a user, their first organization, an Owner membership, and a session — atomically. Reachable without credentials. */
        RegisterRequestInput: {
            displayName: string;
            email: string;
            org: components["schemas"]["CreateOrgRequestInput"];
            password: string;
        };
        /** @description Posts the reversal of an existing journal: a new journal with every line’s side inverted. A journal may be reversed once. */
        ReverseJournalRequest: {
            /** @description The reversal’s own entry date, which must itself fall in an open period. */
            date: components["schemas"]["CalendarDate"];
            memo?: string;
        };
        /** @description Posts the reversal of an existing journal: a new journal with every line’s side inverted. A journal may be reversed once. */
        ReverseJournalRequestInput: {
            /** @description The reversal’s own entry date, which must itself fall in an open period. */
            date: components["schemas"]["CalendarDateInput"];
            memo?: string;
        };
        /** @description Switches the session’s active organization. The role returned is the one held in the new org, never carried across the switch. */
        SwitchActiveOrgRequest: {
            /** Format: uuid */
            orgId: string;
        };
        /** @description Switches the session’s active organization. The role returned is the one held in the new org, never carried across the switch. */
        SwitchActiveOrgRequestInput: {
            /** Format: uuid */
            orgId: string;
        };
        /** @description Debit and credit totals per account plus the org-wide totals, which must be equal. A direct aggregation over journal lines — there is no balance cache anywhere in M1. */
        TrialBalance: {
            /** @description The upper bound that was applied, or null when every posting to date is in. */
            asOf: components["schemas"]["CalendarDate"] | null;
            /** @description `totalDebits - totalCredits`. Always `"0"` for a consistent ledger. Reported rather than asserted, so a discrepancy is visible instead of being converted into an error. */
            difference: components["schemas"]["MinorUnits"];
            rows: components["schemas"]["TrialBalanceRow"][];
            totalCredits: components["schemas"]["MinorUnits"];
            totalDebits: components["schemas"]["MinorUnits"];
        };
        /** @description Debit and credit totals per account plus the org-wide totals, which must be equal. A direct aggregation over journal lines — there is no balance cache anywhere in M1. */
        TrialBalanceInput: {
            /** @description The upper bound that was applied, or null when every posting to date is in. */
            asOf: components["schemas"]["CalendarDateInput"] | null;
            /** @description `totalDebits - totalCredits`. Always `"0"` for a consistent ledger. Reported rather than asserted, so a discrepancy is visible instead of being converted into an error. */
            difference: components["schemas"]["MinorUnitsInput"];
            rows: components["schemas"]["TrialBalanceRowInput"][];
            totalCredits: components["schemas"]["MinorUnitsInput"];
            totalDebits: components["schemas"]["MinorUnitsInput"];
        };
        /** @description One account’s totals. Accounts with no postings appear with zeros — a trial balance that silently omitted them would hide a chart-of-accounts mistake exactly when someone is looking for one. */
        TrialBalanceRow: {
            /** Format: uuid */
            accountId: string;
            /** @description `debits - credits`. Negative means the account is net credit. */
            balance: components["schemas"]["MinorUnits"];
            code: string;
            credits: components["schemas"]["MinorUnits"];
            debits: components["schemas"]["MinorUnits"];
            name: string;
            /** @enum {string} */
            normalBalance: "debit" | "credit";
            /** @enum {string} */
            type: "asset" | "liability" | "equity" | "revenue" | "expense";
        };
        /** @description One account’s totals. Accounts with no postings appear with zeros — a trial balance that silently omitted them would hide a chart-of-accounts mistake exactly when someone is looking for one. */
        TrialBalanceRowInput: {
            /** Format: uuid */
            accountId: string;
            /** @description `debits - credits`. Negative means the account is net credit. */
            balance: components["schemas"]["MinorUnitsInput"];
            code: string;
            credits: components["schemas"]["MinorUnitsInput"];
            debits: components["schemas"]["MinorUnitsInput"];
            name: string;
            /** @enum {string} */
            normalBalance: "debit" | "credit";
            /** @enum {string} */
            type: "asset" | "liability" | "equity" | "revenue" | "expense";
        };
        /** @description Partial update. An absent field is unchanged; `description: null` clears it and `parentAccountId: null` makes the account top-level. `code` is immutable and is not accepted. `type` and `normalBalance` are refused once the account has postings. */
        UpdateAccountRequest: {
            description?: string | null;
            /** @description Display name, e.g. `Operating bank account`. */
            name?: string;
            /**
             * @description The side that increases this account. Stored, never derived from `type`, because contra accounts are real: accumulated depreciation is an `asset` whose normal balance is `credit`, as is an allowance for doubtful accounts. No constraint ties the two fields together — see the `accounts` commentary in migration 0002_ledger.
             * @enum {string}
             */
            normalBalance?: "debit" | "credit";
            parentAccountId?: string | null;
            /**
             * @description Which of the five statement categories the account belongs to. Determines where it appears in reports; it does not determine `normalBalance`.
             * @enum {string}
             */
            type?: "asset" | "liability" | "equity" | "revenue" | "expense";
        };
        /** @description Partial update. An absent field is unchanged; `description: null` clears it and `parentAccountId: null` makes the account top-level. `code` is immutable and is not accepted. `type` and `normalBalance` are refused once the account has postings. */
        UpdateAccountRequestInput: {
            description?: string | null;
            /** @description Display name, e.g. `Operating bank account`. */
            name?: string;
            /**
             * @description The side that increases this account. Stored, never derived from `type`, because contra accounts are real: accumulated depreciation is an `asset` whose normal balance is `credit`, as is an allowance for doubtful accounts. No constraint ties the two fields together — see the `accounts` commentary in migration 0002_ledger.
             * @enum {string}
             */
            normalBalance?: "debit" | "credit";
            parentAccountId?: string | null;
            /**
             * @description Which of the five statement categories the account belongs to. Determines where it appears in reports; it does not determine `normalBalance`.
             * @enum {string}
             */
            type?: "asset" | "liability" | "equity" | "revenue" | "expense";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness only. Reports no dependency state — see the route commentary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                type?: "asset" | "liability" | "equity" | "revenue" | "expense";
                /** @description Accepts `true`/`false` (and `1`/`0`, `yes`/`no`, `on`/`off`). Omitted matches active and inactive accounts alike. */
                isActive?: string;
                /** @description How many accounts to return, at most. Over the maximum is refused rather than clamped, so a short page always means the list is short. */
                limit?: number;
                cursor?: components["schemas"]["PageCursorInput"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountPage"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deactivateAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reactivateAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallerIdentity"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listFiscalPeriods: {
        parameters: {
            query?: {
                /** @description A posting may only land in an `open` period (A4). Closing is the routine monthly soft close; reopening withdraws a statement that may already have been relied on, and needs a separate permission. */
                status?: "open" | "closed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiscalPeriodList"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createFiscalPeriod: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFiscalPeriodRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiscalPeriod"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    closeFiscalPeriod: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                periodId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiscalPeriod"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reopenFiscalPeriod: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                periodId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiscalPeriod"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateFiscalYear: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateFiscalYearRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedFiscalYear"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listJournals: {
        parameters: {
            query?: {
                /** @description How many journals to return, at most. Over the maximum is refused rather than clamped, so a short page always means the list is short. */
                limit?: number;
                cursor?: components["schemas"]["PageCursorInput"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalPage"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postJournal: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostJournalRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostedJournal"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reverseJournal: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path: {
                journalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseJournalRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostedJournal"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listOrgMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembershipList"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembership"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    switchActiveOrg: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every write (spec §12). Send one unique value per logical request and reuse it verbatim when retrying: the same key with the same request replays the original outcome, and the same key with a different request is refused with `idempotency_key_conflict`. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchActiveOrgRequestInput"];
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembership"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTrialBalance: {
        parameters: {
            query?: {
                asOf?: components["schemas"]["CalendarDateInput"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrialBalance"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
